#!/bin/sh

set -e

UPSTREAM_DOWNLOAD_PAGE=https://nekojishi.tw/down.html
UPSTREAM_DOWNLOAD_URL='https://nekojishi.tw/demo/Nekojishi_${VARIANT}${VERSION}-pc.zip'
FILENAME='Nekojishi_${VARIANT}${VERSION}-pc.zip'

TEMP_DIR=/var/cache/nekojishi-installer/
INSTALL_DIR=/usr/share/games/nekojishi/

die_hard() {
	echo "ERROR: $1" >&2
	exit 1
}

[ `whoami` = "root" ] || die_hard "must be root"

show_usage() {
	echo "Usage:"
	echo "  nekojishi-installer --install"
	echo "  nekojishi-installer --install --nsfw"
	echo "  nekojishi-installer --uninstall"
	exit 1
}

getopt_temp=`getopt -o iu --long install,uninstall,nsfw -n 'nekojishi-installer' -- "$@"` || show_usage

eval set -- "$getopt_temp" || show_usage

ACTION=none
VARIANT=Standard # Standard, Limited
FILE=

while [ true ]
do
	case "$1" in
		-i|--install)
			ACTION="--install"
			shift
			;;
		-u|--uninstall)
			ACTION="--uninstall"
			shift
			;;
		--nsfw)
			VARIANT=Limited
			shift
			;;
		--)
			shift
			break
			;;
		*)
			echo "Internal error!" >&2
			exit 1
			;;
	esac
done

get_upstream_version() {
	VERSION=$(wget -qO- $UPSTREAM_DOWNLOAD_PAGE | awk 'match($0, /Nekojishi_Standard(.+)-pc\.zip/, ary){print ary[1]}')
}

get_local_version() {
	LOCAL_VERSION=$(cat ${INSTALL_DIR}version 2>/dev/null || true)
	LOCAL_VARIANT=$(cat ${INSTALL_DIR}variant 2>/dev/null || true)
}

download() {
	url=$(eval echo $UPSTREAM_DOWNLOAD_URL)
	wget -O $FILE $url
}

extract() {
	mkdir -p $INSTALL_DIR/tl/None
	unzip -j $FILE "Nekojishi-pc/game/*.rpa" "Nekojishi-pc/ch-log*" -d $INSTALL_DIR
	unzip -j $FILE "Nekojishi-pc/game/tl/None/*" -d ${INSTALL_DIR}tl/None
}

mark_version() {
	echo $VERSION > ${INSTALL_DIR}version
	echo $VARIANT > ${INSTALL_DIR}variant
}

uninstall() {
	rm -rf ${INSTALL_DIR}*
}

clean_up() {
	rm -f ${TEMP_DIR}*
}

case "$ACTION" in

	--install)
		get_upstream_version
		get_local_version
		if [ "$VERSION" = "$LOCAL_VERSION" ] && [ "$VARIANT" = "$LOCAL_VARIANT" ]; then
			echo "Exact version and variant found."
			clean_up
			exit 0
		fi
		filename=$(eval echo $FILENAME)
		FILE=$TEMP_DIR$filename
		download
		extract
		mark_version
		;;

	--uninstall)
		uninstall
		;;

	*)
		show_usage
		;;

esac

clean_up
