#!/bin/sh

set -e

donate_info() {
	# Users may get the package without going to the website, so
	# displaying this message is important
	echo ""
	echo "If you like this game, please consider buying (donating) the game and"
	echo "merchandises at:"
	echo "https://store.nekojishi.tw/en/shop/"
	echo ""
}

. /usr/share/debconf/confmodule

case "$1" in
    configure)
    	donate_info

    	db_input high nekojishi-installer/variant
	db_go

    	db_get nekojishi-installer/variant
	if [ "$RET" = "NSFW" ]; then
		nekojishi-installer --install --nsfw
	else
		nekojishi-installer --install
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

