#!/bin/sh

set -e

case "$1" in
    remove|deconfigure)
        nekojishi-installer --uninstall || true
    ;;

    upgrade|failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
